"""Description refresher - generate and cache L1/L2 descriptions.

This module handles:
1. Connecting to MCP servers temporarily
2. Fetching tool definitions
3. Generating capability summaries from keyword tags
4. Caching descriptions to .mcp-gateway/descriptions.yaml
"""

from __future__ import annotations

import logging
import asyncio
from datetime import datetime, timezone
from pathlib import Path

import yaml

from pmcp.manifest.loader import Manifest, ServerConfig, load_manifest
from pmcp.manifest.version_checker import (
    compare_versions,
    detect_package_type,
    get_package_version,
)
from pmcp.types import (
    DescriptionsCache,
    GeneratedServerDescriptions,
    PrebuiltToolInfo,
)

logger = logging.getLogger(__name__)

# Gateway version for cache metadata
GATEWAY_VERSION = "1.0.0"

# Default cache directory
DEFAULT_CACHE_DIR = Path(".mcp-gateway")
DESCRIPTIONS_CACHE_FILE = "descriptions.yaml"
REFRESH_VERSION_LOOKUP_CONCURRENCY = 8


def get_cache_path(cache_dir: Path | None = None) -> Path:
    """Get the path to the descriptions cache file."""
    if cache_dir is None:
        cache_dir = DEFAULT_CACHE_DIR
    return cache_dir / DESCRIPTIONS_CACHE_FILE


def load_descriptions_cache(cache_path: Path | None = None) -> DescriptionsCache | None:
    """Load cached descriptions from file."""
    if cache_path is None:
        cache_path = get_cache_path()

    if not cache_path.exists():
        logger.debug(f"No descriptions cache found at {cache_path}")
        return None

    try:
        with open(cache_path, "r") as f:
            data = yaml.safe_load(f)

        if not data:
            return None

        # Parse servers
        servers = {}
        for name, server_data in data.get("servers", {}).items():
            tools = [PrebuiltToolInfo(**t) for t in server_data.get("tools", [])]
            servers[name] = GeneratedServerDescriptions(
                package=server_data.get("package", ""),
                # Default to None, not "": an absent value must stay
                # distinguishable from a recorded empty one.
                package_type=server_data.get("package_type"),
                version=server_data.get("version", ""),
                generated_at=server_data.get("generated_at", ""),
                capability_summary=server_data.get("capability_summary", ""),
                tools=tools,
            )

        return DescriptionsCache(
            generated_at=data.get("generated_at", ""),
            gateway_version=data.get("gateway_version", ""),
            servers=servers,
        )

    except Exception as e:
        logger.warning(f"Failed to load descriptions cache: {e}")
        return None


def save_descriptions_cache(
    cache: DescriptionsCache, cache_path: Path | None = None
) -> None:
    """Save descriptions cache to file."""
    if cache_path is None:
        cache_path = get_cache_path()

    # Ensure directory exists
    cache_path.parent.mkdir(parents=True, exist_ok=True)

    data = {
        "generated_at": cache.generated_at,
        "gateway_version": cache.gateway_version,
        "servers": {
            name: {
                "package": desc.package,
                "package_type": desc.package_type,
                "version": desc.version,
                "generated_at": desc.generated_at,
                "capability_summary": desc.capability_summary,
                "tools": [
                    {
                        "name": tool.name,
                        "description": tool.description,
                        "short_description": tool.short_description,
                        "tags": list(tool.tags),
                        "risk_hint": tool.risk_hint,
                    }
                    for tool in desc.tools
                ],
            }
            for name, desc in cache.servers.items()
        },
    }

    with open(cache_path, "w") as f:
        f.write("# Auto-generated by pmcp refresh\n")
        f.write("# Do not edit manually - regenerate with: pmcp refresh\n\n")
        yaml.safe_dump(data, f, sort_keys=False, allow_unicode=True)

    logger.info(f"Saved descriptions cache to {cache_path}")


def _indent_multiline(text: str, indent: int) -> str:
    """Indent multiline text for YAML."""
    lines = text.strip().split("\n")
    prefix = " " * indent
    return "\n".join(prefix + line for line in lines)


def _escape_yaml_string(text: str) -> str:
    """Escape special characters in YAML strings."""
    return text.replace('"', '\\"').replace("\n", " ").strip()


def _extract_tags(tool_name: str, description: str) -> list[str]:
    """Extract tags from tool name and description."""
    tags = []
    text = f"{tool_name} {description}".lower()

    tag_keywords = {
        "browser": ["browser", "navigate", "click", "screenshot", "dom", "page"],
        "file": ["file", "read", "write", "directory", "folder", "path"],
        "db": ["database", "query", "sql", "table", "postgres", "sqlite"],
        "git": ["git", "commit", "branch", "repository", "push", "pull"],
        "http": ["http", "fetch", "request", "api", "url", "download"],
        "search": ["search", "find", "query", "lookup", "resolve"],
        "docs": ["documentation", "docs", "reference", "library"],
        "code": ["code", "function", "class", "module", "script"],
    }

    for tag, keywords in tag_keywords.items():
        if any(kw in text for kw in keywords):
            tags.append(tag)

    return tags or ["general"]


def _infer_risk(tool_name: str, description: str) -> str:
    """Infer risk level from tool name and description."""
    text = f"{tool_name} {description}".lower()

    high_risk = [
        "delete",
        "remove",
        "drop",
        "execute",
        "run",
        "write",
        "modify",
        "create",
        "post",
    ]
    medium_risk = ["navigate", "click", "submit", "input", "form"]

    if any(kw in text for kw in high_risk):
        return "high"
    if any(kw in text for kw in medium_risk):
        return "medium"
    return "low"


# A package name or type that carries no identity information. `detect_package_type`
# reports `"unknown"` for a command it cannot classify, and a cache written before
# `package_type` existed reports `None`.
_UNIDENTIFIED = ("", "unknown")


def _same_package(
    cached_package: str,
    cached_type: str | None,
    configured_package: str | None,
    configured_type: str | None,
) -> bool:
    """Whether a cached entry and a configured server describe the same package.

    Cached descriptions are paired with a server config by NAME, and freshness is
    then decided by comparing versions. That answers "is the cache old" but not
    "does the cache still describe this package", so a swap at an equal version
    -- `old-pkg@1.0.0` cached against `new-pkg@1.0.0` configured -- serves the
    wrong package's tool descriptions indefinitely.

    **An unknown side means "cannot confirm identity", which resolves to
    refresh -- never to "cannot compare, so skip the check."** Any of the four
    values being empty, `None` or `"unknown"` therefore returns `False`, and at
    every call site `False` means the freshness short-circuit does not fire.
    The second reading is the natural one to reach for and is the same
    fail-open collapse as `not is_version_newer(...)`, which shipped three
    times (Consiliency/pmcp#155, #156, #163).

    The type arms are not decorative: `package` is a bare name with no
    ecosystem, so npm `foo` and pypi `foo` are indistinguishable without it,
    and npm/pypi/cargo all produce orderable *release* versions so
    `compare_versions` never reports them `incomparable`.
    """
    for value in (cached_package, cached_type, configured_package, configured_type):
        if value is None or value in _UNIDENTIFIED:
            return False
    return cached_package == configured_package and cached_type == configured_type


async def refresh_server(
    server_config: ServerConfig,
    existing_cache: GeneratedServerDescriptions | None = None,
    force: bool = False,
) -> GeneratedServerDescriptions | None:
    """
    Refresh descriptions for a single server.

    This temporarily connects to the server, fetches tools, and generates summaries.

    Args:
        server_config: Server configuration from manifest
        existing_cache: Existing cached descriptions (for staleness check)
        force: Force regeneration even if not stale

    Returns:
        Generated descriptions or None if failed
    """
    from mcp import ClientSession, StdioServerParameters
    from mcp.client.stdio import stdio_client

    server_name = server_config.name

    # Determine package info. This MUST precede the freshness short-circuit
    # below: the short-circuit cannot consult identity unless identity has
    # already been resolved, which is why this resolution moved up here rather
    # than being duplicated (Consiliency/pmcp#178, EC-UPDPATH-2).
    pkg_type, pkg_name = detect_package_type(
        server_config.command,
        server_config.args,
        # The manifest's `ServerConfig` carries `extra_env` and NO `cwd`, so the
        # overlay is `extra_env` and the effective cwd is this process's.
        # `extra_env` is the right thing to pass rather than the merged
        # `sanitized_subprocess_env` result: the gate asks whether THIS SERVER'S
        # configuration can redirect npm's resolution, and a merged environment
        # always carries PATH and HOME, which would refuse every npm server on
        # every host. The credential this server also receives at spawn cannot
        # match the gate's key patterns (`npm_config_*`, PATH, HOME, NODE_PATH,
        # NODE_OPTIONS, PREFIX, NVM_*), so omitting it changes no answer.
        server_config.extra_env,
        None,
    )
    if not pkg_name:
        pkg_name = f"{server_config.command} {' '.join(server_config.args)}"

    # Check for staleness if we have cached data
    if existing_cache and not force:
        # Get current package version
        version, fetched_type = await get_package_version(
            server_config.command,
            server_config.args,
            server_config.extra_env,
            None,
        )

        # Identity before freshness: a version comparison is only meaningful
        # once the cache is known to describe the package that is configured.
        if (
            version
            and _same_package(
                existing_cache.package,
                existing_cache.package_type,
                pkg_name,
                pkg_type,
            )
            and compare_versions(existing_cache.version, version, fetched_type)
            == "not_newer"
        ):
            logger.debug(
                f"Server {server_name} is up to date (v{existing_cache.version})"
            )
            return existing_cache

    logger.info(f"Refreshing descriptions for {server_name}...")

    # Get version
    version, _ = await get_package_version(
        server_config.command, server_config.args, server_config.extra_env, None
    )
    version = version or "unknown"

    try:
        # Create server parameters
        server_params = StdioServerParameters(
            command=server_config.command,
            args=server_config.args,
        )

        # Connect and fetch tools
        async with stdio_client(server_params) as (read, write):
            async with ClientSession(read, write) as session:
                await session.initialize()

                # List tools
                tools_result = await session.list_tools()
                tools = tools_result.tools

                logger.info(f"Found {len(tools)} tools for {server_name}")

                # Convert to PrebuiltToolInfo
                prebuilt_tools = []
                for tool in tools:
                    name = tool.name
                    description = tool.description or ""
                    short_desc = (
                        description[:100] + "..."
                        if len(description) > 100
                        else description
                    )

                    prebuilt_tools.append(
                        PrebuiltToolInfo(
                            name=name,
                            description=description,
                            short_description=short_desc,
                            tags=_extract_tags(name, description),
                            risk_hint=_infer_risk(name, description),
                        )
                    )

                # Generate capability summary
                capability_summary = await _generate_capability_summary(
                    server_name, prebuilt_tools
                )

                return GeneratedServerDescriptions(
                    package=pkg_name,
                    package_type=pkg_type,
                    version=version,
                    generated_at=datetime.now(timezone.utc).isoformat(),
                    capability_summary=capability_summary,
                    tools=prebuilt_tools,
                )

    except Exception as e:
        logger.error(f"Failed to refresh {server_name}: {e}")
        return None


async def _generate_capability_summary(
    server_name: str, tools: list[PrebuiltToolInfo]
) -> str:
    """Generate capability summary for a server using keyword tags."""
    if not tools:
        return f"• {server_name} (0 tools): No tools available"

    capabilities = set()
    for tool in tools:
        for tag in tool.tags:
            capabilities.add(tag)

    cap_str = ", ".join(sorted(capabilities)[:5])
    return f"• {server_name.title()} ({len(tools)} tools): {cap_str}"


async def refresh_all(
    manifest: Manifest | None = None,
    cache_path: Path | None = None,
    force: bool = False,
    servers: list[str] | None = None,
) -> DescriptionsCache:
    """
    Refresh descriptions for all or selected servers.

    Args:
        manifest: Manifest to use (loads default if None)
        cache_path: Path to cache file
        force: Force regeneration even if not stale
        servers: List of server names to refresh (all if None)

    Returns:
        Updated descriptions cache
    """
    if manifest is None:
        manifest = load_manifest()

    # Load existing cache
    existing_cache = load_descriptions_cache(cache_path)
    existing_servers = existing_cache.servers if existing_cache else {}

    # Determine which servers to refresh
    target_servers = servers or list(manifest.servers.keys())

    # Refresh each server with bounded concurrency
    new_servers: dict[str, GeneratedServerDescriptions] = {}
    semaphore = asyncio.Semaphore(REFRESH_VERSION_LOOKUP_CONCURRENCY)

    # Targeted servers whose cached entry does not describe the package the
    # manifest now configures. `refresh_all` assembles the (cached, configured)
    # pair itself, so it must apply the gate rather than rely on the callee, and
    # such an entry must not come back through EITHER failure path below: the
    # None/raise fallback returning it as a live result, or the merge loop at
    # the end writing it straight back to disk. Dropping the entry when
    # regeneration fails is acceptable; writing the wrong package's
    # descriptions back is not.
    mismatched: set[str] = set()

    async def refresh_target(
        name: str,
    ) -> tuple[str, GeneratedServerDescriptions | None]:
        server_config = manifest.get_server(name)
        if not server_config:
            logger.warning(f"Server {name} not found in manifest")
            return name, None

        existing = existing_servers.get(name)
        if existing is not None:
            cfg_type, cfg_name = detect_package_type(
                server_config.command,
                server_config.args,
                server_config.extra_env,
                None,
            )
            if not _same_package(
                existing.package, existing.package_type, cfg_name, cfg_type
            ):
                logger.info(
                    f"Cached descriptions for {name} do not confirm the "
                    f"configured package (cached {existing.package!r}); "
                    "discarding them and regenerating"
                )
                mismatched.add(name)
                existing = None

        try:
            async with semaphore:
                result = await refresh_server(server_config, existing, force)
            if result:
                return name, result
            elif existing:
                # Keep existing if refresh failed
                return name, existing
        except Exception as e:
            logger.error(f"Error refreshing {name}: {e}")
            if existing:
                return name, existing
        return name, None

    for name, result in await asyncio.gather(
        *(refresh_target(name) for name in target_servers)
    ):
        if result:
            new_servers[name] = result

    # Merge with existing cache (keep servers not in target list). A targeted
    # entry that failed the identity gate is deliberately absent from
    # `new_servers`; re-adding it here would undo the gate.
    for name, desc in existing_servers.items():
        if name not in new_servers and name not in mismatched:
            new_servers[name] = desc

    # Create new cache
    cache = DescriptionsCache(
        generated_at=datetime.now(timezone.utc).isoformat(),
        gateway_version=GATEWAY_VERSION,
        servers=new_servers,
    )

    # Save cache
    save_descriptions_cache(cache, cache_path)

    return cache


async def check_staleness(
    manifest: Manifest | None = None,
    cache_path: Path | None = None,
) -> dict[str, tuple[str, str]]:
    """
    Check which servers have newer versions available.

    Returns:
        Dict of server_name -> (cached_version, latest_version) for stale servers
    """
    if manifest is None:
        manifest = load_manifest()

    existing_cache = load_descriptions_cache(cache_path)
    if not existing_cache:
        logger.info("No cache found, all servers need refresh")
        return {}

    stale_servers: dict[str, tuple[str, str]] = {}

    for name, desc in existing_cache.servers.items():
        server_config = manifest.get_server(name)
        if not server_config:
            continue

        cfg_type, cfg_name = detect_package_type(
            server_config.command, server_config.args, server_config.extra_env, None
        )

        version, pkg_type = await get_package_version(
            server_config.command, server_config.args, server_config.extra_env, None
        )

        # NOTE the inverted polarity relative to `refresh_server`. There, a
        # match plus `not_newer` SKIPS a refresh, so an identity mismatch
        # withholds the skip. Here, `newer` ADDS to the stale dict, so an
        # identity mismatch must ADD -- porting that guard mechanically would
        # report a swapped package as up to date, which is the defect.
        if not _same_package(desc.package, desc.package_type, cfg_name, cfg_type):
            stale_servers[name] = (desc.version, version or "unknown")
            logger.info(
                f"Server {name} is stale: cached package {desc.package!r} does "
                f"not confirm the configured package {cfg_name!r}"
            )
            continue

        if version and compare_versions(desc.version, version, pkg_type) == "newer":
            stale_servers[name] = (desc.version, version)
            logger.info(f"Server {name} is stale: {desc.version} -> {version}")

    return stale_servers
